@startmindmap
<style>
node {
    Padding 12
    Margin 3
    HorizontalAlignment center
    LineColor Teal
    LineThickness 2.0
    BackgroundColor LemonChiffon
    RoundCorner 20
    MaximumWidth 100
}

rootNode {
    LineStyle 8.0;3.0
    LineColor Teal
    BackgroundColor LemonChiffon
    LineThickness 1.0
    RoundCorner 0
    Shadowing 0.0
}

leafNode {
    LineColor Teal
    RoundCorner 0
    Padding 3
}

arrow {
    LineStyle 4
    LineThickness 1
    LineColor blue
}
</style>

* 源義国
	* 足利義康*1\n[足利氏]
		* 義清*a2
			*_ 畠山義純\n[畠山氏]
			*_ 桃井義助\n[桃井氏]
			* 義氏*a3
				*_ 吉良長氏\n[吉良氏]
				* 泰氏*a4
					*_ 斯波家氏\n[斯波氏]
					*_ 渋川義顕\n[渋川氏]
					* 頼氏*a5
						* 家時*a6
							* 貞氏*a7
								* 高義
								* 高氏*a8,*b1\n(尊氏)\n[足利将軍家]
									* 竹若丸
									* >直冬
									* 義詮*b2
										* 千寿王
										* 義満*b3
											*_ 尊満
											* 義持*b4
												* 義量*b5
												*_ 三淵持清\n[三淵氏]
												*_ <持氏
											* 義嗣
											* 義教*b6
												* 義勝*b7
												*_ 義永
												* 政知*f1\n[堀越公方]
													* 茶々丸*f2
													* >義澄*b11
													* 潤童子
													*_ >小田政治
												* 義政*b8
													* 義尚*b9
													*_ 等賢同山
													*_ 義覚
													*_ 光山聖俊
													* <義視*c1\n[西幕府相公]
														* >義材*b10\n(義尹,義稙)
														*_ 実相院義忠
														*_ 慈照院周嘉
														*_ 水野義純
														*_ 照禅院了玄
													* <義材*b10\n(義尹,義稙)
														* 竹王丸
														* <義晴*b12
															* 義輝*b13
																* 輝若丸
															* 義昭*b15
																*_ 義尋
																	*_ 実相院義尊
																	*_ 円満院常尊
																*_ 一色義喬
																*_ 永山義在
																*_ 矢島秀行
															*_ 周暠
															*_ 白鳥義久
														* <義維
															* 義栄*b14
															* 義助
																* 義種
																	*_ 義次\n[平島足利家]
																	* 義俊
																	* 宗徳
																* 義遠
															* 義任
														* <義堯
														* <六角義実
													* <義澄*b11
														* >義晴*b12
														* >義維
												* 義観
												* >義視*c1\n[西幕府相公]
												*_ 義堯
												*_ 聖智
												*_ <小倉宮教尊
												*_ <教賢
												*_ <義快
												*_ <政超
											*_ 法尊
											* 虎山永隆
											* 梶井義承
											* 宝幢若公
											*_ 仁和寺法尊
											*_ 大覚寺義昭
											*_ 本覚院満守
											*_ <斯波義重
											*_ <三宝院満済
										* 満詮
										* 柏庭清祖
										* 廷用宗器
									* 基氏*d1\n[鎌倉公方]
										* 氏満*d2
											* 満兼*d3
												* 持氏*d4
													* 義久
													* 春王丸
													* 安王丸
													* 成氏*d5,*e1\n[古河公方]
														* 政氏*e2
															* 高氏*e3\n(高基,義基)
																* 晴氏*e4
																	* 藤氏
																	* 義氏*e5
																	* 藤政
																	* 輝氏
																	* 家国
																*_ 高実
																*_ 雲岳周揚
																*_ 晴直\n(上杉憲寛)
																*_ 大内晴泰
															* 義明
															* 基頼
															*_ 貞岩昌永?
														*_ 義綱\n(上杉顕実)
														*_ 貞岩昌永?
													* 尊敒
													* 成潤
												* >持仲
											* 満直
											* 満隆
												* 満康
												* <持仲
											* 満貞
												*_ 稲村満房
											* 満季
												* 満氏
									* 鶴王
								* 高国\n(直義)
									* 如意丸
									* <直冬
										* 冬氏
											* 義尊
											* 義将
										*_ 成直
										*_ 等珊
										*_ 等章
										*_ 乾桃
										*_ 宝山乾珍
								* 源淋
					*_ 石塔頼茂\n[石塔氏]
					*_ 一色公深\n[一色氏]
					*_ 上野義弁\n[上野氏]
					*_ 小俣賢宝\n[小俣氏]
					*_ 加古基氏\n[加古氏]
					*_ 覚海
					*_ 麻植氏継\n[麻植氏]
				*_ 吉良義継\n[奥州吉良氏]
			* <義胤
		* 義長
		* 義兼
		* 義房
	*_ 義重\n[新田氏]
	*_ 季邦
@endmindmap
