@startmindmap
<style>
node {
    Padding 12
    Margin 3
    HorizontalAlignment center
    LineColor Teal
    LineThickness 2.0
    BackgroundColor LemonChiffon
    RoundCorner 20
    MaximumWidth 100
}

rootNode {
    LineStyle 8.0;3.0
    LineColor Teal
    BackgroundColor LemonChiffon
    LineThickness 1.0
    RoundCorner 0
    Shadowing 0.0
}

leafNode {
    LineColor Teal
    RoundCorner 0
    Padding 3
}

arrow {
    LineStyle 4
    LineThickness 1
    LineColor blue
}
</style>

* 清和天皇
	* 貞純親王
		* 源経基
			* 満仲
				* 頼信*1\n[河内源氏]
					* 頼義*2
						* 義家*3
							* 義宗
							* 義親
								* 義信
									* 延朗
									* 義政
									* 義資
								* 義俊
								* 親泰
								* 為義*5
									* 義朝*6
										* 義平
										* 朝長
										* 頼朝*7
											* 頼家*8
											* 実朝*9
										* 義門
										* 希義
											*_ 希望\n[土佐吉良氏]
										* 範頼
										* 全成
										* 義円
										* 義経
									*_ 義賢\n[木曽氏]
									* 義広
									* 頼賢
									* 頼仲
									* 為宗
									* 為成
									* 為朝
									* 為仲
									* 行家
										*_ 光家\n[紀伊新宮氏]
								* 義行
								* 宗清
							* 義忠*4
								* 経国
									*_ 盛経\n[稲沢氏]
								* 義高
									* 義成
										* 義俊
								* 忠宗
								* 義清
									* 義久
										* 義高
								* 義雄
							* 義国
								*_ 義重\n[新田氏]
								*_ 義康\n[足利氏]
								* 季邦
							*_ 義時\n[石川氏]
							*_ 義隆\n[毛利氏]
						* 義綱
							* 義弘
							* 義俊
							* 義明
							* 義仲
							* 義範
							* 義公
							*_ 義直\n[石橋氏]
						* 義光
							*_ 義業\n[佐竹氏]
							*_ 実光\n[石井氏]
							*_ 義清\n[甲斐源氏]
							*_ 盛義\n[信濃平賀氏]
							* 親義
						* 快誉
					*_ 頼清\n[信濃村上氏]
					*_ 頼季\n[信濃井上氏]
					*_ 頼任\n[信濃河内氏]
					* 義政
				*_ 頼親\n[大和源氏]
				*_ 頼光\n[摂津源氏]
			* 満政
				* 忠重
					* 定宗
						* 重宗
							* 重実
							*_ 重長\n[木田氏]
							* 重時
								* <実時
								* <季遠
									* 光季
									*_ 季貞\n[飯富氏]
								* <重俊
								* <光成
								* <重範
							* 重高
							*_ 重親\n[小島氏]
					* 定重
				* 忠隆
					* 斉頼
						* 良行
						* 良季
						*_ 惟家\n[善積氏]
						* 高仲
						* 能行
						* 忠清
						* 隆祐
						* 斉家
					* 重隆
					* 忠清
					* 隆仲
					* 重明
					* 義経
				* 忠国
			* 満季
				* <致公
					* 致任
						* 定俊
							* 成貞
							* 成實
							*_ 為経\n[高屋氏]
							* 季信
							* 忠政
							* 忠尊
							* 兼源
						* 憲尊
				*_ >満頼
			* 満実
			* 満快
				* 満国
				* 行頼（行満）
				* 頼季
			* 満生
			* 満重
			*_ <満頼\n[美濃多田氏]
		* 経生
@endmindmap